{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "import ssl\n",
    "\n",
    "ssl._create_default_https_context = ssl._create_unverified_context"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Neighborhood</th>\n",
       "      <th>Id</th>\n",
       "      <th>Estimate; Total:</th>\n",
       "      <th>Margin of Error; Total:</th>\n",
       "      <th>Estimate; Total: - With wage or salary income</th>\n",
       "      <th>Margin of Error; Total: - With wage or salary income</th>\n",
       "      <th>Estimate; Total: - No wage or salary income</th>\n",
       "      <th>Margin of Error; Total: - No wage or salary income</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Allegheny Center</td>\n",
       "      <td>1</td>\n",
       "      <td>733.0</td>\n",
       "      <td>103.000000</td>\n",
       "      <td>462.0</td>\n",
       "      <td>94.000000</td>\n",
       "      <td>271.0</td>\n",
       "      <td>87.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Allegheny West</td>\n",
       "      <td>2</td>\n",
       "      <td>150.0</td>\n",
       "      <td>46.000000</td>\n",
       "      <td>120.0</td>\n",
       "      <td>40.000000</td>\n",
       "      <td>30.0</td>\n",
       "      <td>26.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Allentown</td>\n",
       "      <td>3</td>\n",
       "      <td>1138.0</td>\n",
       "      <td>152.751432</td>\n",
       "      <td>772.0</td>\n",
       "      <td>146.771932</td>\n",
       "      <td>366.0</td>\n",
       "      <td>109.389213</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Arlington</td>\n",
       "      <td>4</td>\n",
       "      <td>685.0</td>\n",
       "      <td>105.366029</td>\n",
       "      <td>566.0</td>\n",
       "      <td>104.589674</td>\n",
       "      <td>119.0</td>\n",
       "      <td>44.452222</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Arlington Heights</td>\n",
       "      <td>5</td>\n",
       "      <td>170.0</td>\n",
       "      <td>69.000000</td>\n",
       "      <td>96.0</td>\n",
       "      <td>58.000000</td>\n",
       "      <td>74.0</td>\n",
       "      <td>52.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>Banksville</td>\n",
       "      <td>6</td>\n",
       "      <td>2002.0</td>\n",
       "      <td>224.986666</td>\n",
       "      <td>1596.0</td>\n",
       "      <td>226.477372</td>\n",
       "      <td>406.0</td>\n",
       "      <td>145.168867</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>Bedford Dwellings</td>\n",
       "      <td>7</td>\n",
       "      <td>684.0</td>\n",
       "      <td>63.000000</td>\n",
       "      <td>294.0</td>\n",
       "      <td>69.000000</td>\n",
       "      <td>390.0</td>\n",
       "      <td>77.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>Beechview</td>\n",
       "      <td>8</td>\n",
       "      <td>3557.0</td>\n",
       "      <td>270.051847</td>\n",
       "      <td>2654.0</td>\n",
       "      <td>249.649755</td>\n",
       "      <td>903.0</td>\n",
       "      <td>162.154248</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>Beltzhoover</td>\n",
       "      <td>9</td>\n",
       "      <td>869.0</td>\n",
       "      <td>146.594679</td>\n",
       "      <td>586.0</td>\n",
       "      <td>117.187883</td>\n",
       "      <td>283.0</td>\n",
       "      <td>107.712581</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>Bloomfield</td>\n",
       "      <td>10</td>\n",
       "      <td>4640.0</td>\n",
       "      <td>215.506380</td>\n",
       "      <td>3789.0</td>\n",
       "      <td>223.385317</td>\n",
       "      <td>851.0</td>\n",
       "      <td>117.388245</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "        Neighborhood  Id  Estimate; Total:  Margin of Error; Total:  \\\n",
       "0   Allegheny Center   1             733.0               103.000000   \n",
       "1     Allegheny West   2             150.0                46.000000   \n",
       "2          Allentown   3            1138.0               152.751432   \n",
       "3          Arlington   4             685.0               105.366029   \n",
       "4  Arlington Heights   5             170.0                69.000000   \n",
       "5         Banksville   6            2002.0               224.986666   \n",
       "6  Bedford Dwellings   7             684.0                63.000000   \n",
       "7          Beechview   8            3557.0               270.051847   \n",
       "8        Beltzhoover   9             869.0               146.594679   \n",
       "9         Bloomfield  10            4640.0               215.506380   \n",
       "\n",
       "   Estimate; Total: - With wage or salary income  \\\n",
       "0                                          462.0   \n",
       "1                                          120.0   \n",
       "2                                          772.0   \n",
       "3                                          566.0   \n",
       "4                                           96.0   \n",
       "5                                         1596.0   \n",
       "6                                          294.0   \n",
       "7                                         2654.0   \n",
       "8                                          586.0   \n",
       "9                                         3789.0   \n",
       "\n",
       "   Margin of Error; Total: - With wage or salary income  \\\n",
       "0                                          94.000000      \n",
       "1                                          40.000000      \n",
       "2                                         146.771932      \n",
       "3                                         104.589674      \n",
       "4                                          58.000000      \n",
       "5                                         226.477372      \n",
       "6                                          69.000000      \n",
       "7                                         249.649755      \n",
       "8                                         117.187883      \n",
       "9                                         223.385317      \n",
       "\n",
       "   Estimate; Total: - No wage or salary income  \\\n",
       "0                                        271.0   \n",
       "1                                         30.0   \n",
       "2                                        366.0   \n",
       "3                                        119.0   \n",
       "4                                         74.0   \n",
       "5                                        406.0   \n",
       "6                                        390.0   \n",
       "7                                        903.0   \n",
       "8                                        283.0   \n",
       "9                                        851.0   \n",
       "\n",
       "   Margin of Error; Total: - No wage or salary income  \n",
       "0                                          87.000000   \n",
       "1                                          26.000000   \n",
       "2                                         109.389213   \n",
       "3                                          44.452222   \n",
       "4                                          52.000000   \n",
       "5                                         145.168867   \n",
       "6                                          77.000000   \n",
       "7                                         162.154248   \n",
       "8                                         107.712581   \n",
       "9                                         117.388245   "
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "police_data = pd.read_csv(\"https://data.wprdc.org/dataset/c6265ffb-c86e-4a2c-870b-1aaa0772c449/resource/14abb000-d066-4728-8ffa-227883d6c331/download/wage-or-salary-income-in-the-past-12-months-for-households.csv\")\n",
    "police_data.head(10)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Id</th>\n",
       "      <th>Estimate; Total:</th>\n",
       "      <th>Margin of Error; Total:</th>\n",
       "      <th>Estimate; Total: - With wage or salary income</th>\n",
       "      <th>Margin of Error; Total: - With wage or salary income</th>\n",
       "      <th>Estimate; Total: - No wage or salary income</th>\n",
       "      <th>Margin of Error; Total: - No wage or salary income</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Neighborhood</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>Allegheny Center</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Allegheny West</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Allentown</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Arlington</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Arlington Heights</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Banksville</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Bedford Dwellings</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Beechview</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Beltzhoover</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Bloomfield</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Bluff</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Bon Air</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Brighton Heights</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Brookline</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>California-Kirkbride</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Carrick</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Central Business District</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Central Lawrenceville</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Central Northside</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Central Oakland</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Chartiers City</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Chateau</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Crafton Heights</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Crawford-Roberts</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Duquesne Heights</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>East Allegheny</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>East Carnegie</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>East Hills</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>East Liberty</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Elliott</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Perry North</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Perry South</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Point Breeze</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Point Breeze North</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Polish Hill</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Regent Square</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Ridgemont</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Shadyside</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Sheraden</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>South Oakland</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>South Shore</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>South Side Flats</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>South Side Slopes</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Spring Garden</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Spring Hill-City View</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Squirrel Hill North</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Squirrel Hill South</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>St. Clair</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Stanton Heights</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Strip District</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Summer Hill</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Swisshelm Park</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Terrace Village</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Troy Hill</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Upper Hill</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Upper Lawrenceville</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>West End</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>West Oakland</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Westwood</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Windgap</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>91 rows × 7 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                           Id  Estimate; Total:  Margin of Error; Total:  \\\n",
       "Neighborhood                                                               \n",
       "Allegheny Center            1                 1                        1   \n",
       "Allegheny West              1                 1                        1   \n",
       "Allentown                   1                 1                        1   \n",
       "Arlington                   1                 1                        1   \n",
       "Arlington Heights           1                 1                        1   \n",
       "Banksville                  1                 1                        1   \n",
       "Bedford Dwellings           1                 1                        1   \n",
       "Beechview                   1                 1                        1   \n",
       "Beltzhoover                 1                 1                        1   \n",
       "Bloomfield                  1                 1                        1   \n",
       "Bluff                       1                 1                        1   \n",
       "Bon Air                     1                 1                        1   \n",
       "Brighton Heights            1                 1                        1   \n",
       "Brookline                   1                 1                        1   \n",
       "California-Kirkbride        1                 1                        1   \n",
       "Carrick                     1                 1                        1   \n",
       "Central Business District   1                 1                        1   \n",
       "Central Lawrenceville       1                 1                        1   \n",
       "Central Northside           1                 1                        1   \n",
       "Central Oakland             1                 1                        1   \n",
       "Chartiers City              1                 1                        1   \n",
       "Chateau                     1                 1                        1   \n",
       "Crafton Heights             1                 1                        1   \n",
       "Crawford-Roberts            1                 1                        1   \n",
       "Duquesne Heights            1                 1                        1   \n",
       "East Allegheny              1                 1                        1   \n",
       "East Carnegie               1                 1                        1   \n",
       "East Hills                  1                 1                        1   \n",
       "East Liberty                1                 1                        1   \n",
       "Elliott                     1                 1                        1   \n",
       "...                        ..               ...                      ...   \n",
       "Perry North                 1                 1                        1   \n",
       "Perry South                 1                 1                        1   \n",
       "Point Breeze                1                 1                        1   \n",
       "Point Breeze North          1                 1                        1   \n",
       "Polish Hill                 1                 1                        1   \n",
       "Regent Square               1                 1                        1   \n",
       "Ridgemont                   1                 1                        1   \n",
       "Shadyside                   1                 1                        1   \n",
       "Sheraden                    1                 1                        1   \n",
       "South Oakland               1                 1                        1   \n",
       "South Shore                 1                 1                        1   \n",
       "South Side Flats            1                 1                        1   \n",
       "South Side Slopes           1                 1                        1   \n",
       "Spring Garden               1                 1                        1   \n",
       "Spring Hill-City View       1                 1                        1   \n",
       "Squirrel Hill North         1                 1                        1   \n",
       "Squirrel Hill South         1                 1                        1   \n",
       "St. Clair                   1                 1                        1   \n",
       "Stanton Heights             1                 1                        1   \n",
       "Strip District              1                 1                        1   \n",
       "Summer Hill                 1                 1                        1   \n",
       "Swisshelm Park              1                 1                        1   \n",
       "Terrace Village             1                 1                        1   \n",
       "Troy Hill                   1                 1                        1   \n",
       "Upper Hill                  1                 1                        1   \n",
       "Upper Lawrenceville         1                 1                        1   \n",
       "West End                    1                 1                        1   \n",
       "West Oakland                1                 1                        1   \n",
       "Westwood                    1                 1                        1   \n",
       "Windgap                     1                 1                        1   \n",
       "\n",
       "                           Estimate; Total: - With wage or salary income  \\\n",
       "Neighborhood                                                               \n",
       "Allegheny Center                                                       1   \n",
       "Allegheny West                                                         1   \n",
       "Allentown                                                              1   \n",
       "Arlington                                                              1   \n",
       "Arlington Heights                                                      1   \n",
       "Banksville                                                             1   \n",
       "Bedford Dwellings                                                      1   \n",
       "Beechview                                                              1   \n",
       "Beltzhoover                                                            1   \n",
       "Bloomfield                                                             1   \n",
       "Bluff                                                                  1   \n",
       "Bon Air                                                                1   \n",
       "Brighton Heights                                                       1   \n",
       "Brookline                                                              1   \n",
       "California-Kirkbride                                                   1   \n",
       "Carrick                                                                1   \n",
       "Central Business District                                              1   \n",
       "Central Lawrenceville                                                  1   \n",
       "Central Northside                                                      1   \n",
       "Central Oakland                                                        1   \n",
       "Chartiers City                                                         1   \n",
       "Chateau                                                                1   \n",
       "Crafton Heights                                                        1   \n",
       "Crawford-Roberts                                                       1   \n",
       "Duquesne Heights                                                       1   \n",
       "East Allegheny                                                         1   \n",
       "East Carnegie                                                          1   \n",
       "East Hills                                                             1   \n",
       "East Liberty                                                           1   \n",
       "Elliott                                                                1   \n",
       "...                                                                  ...   \n",
       "Perry North                                                            1   \n",
       "Perry South                                                            1   \n",
       "Point Breeze                                                           1   \n",
       "Point Breeze North                                                     1   \n",
       "Polish Hill                                                            1   \n",
       "Regent Square                                                          1   \n",
       "Ridgemont                                                              1   \n",
       "Shadyside                                                              1   \n",
       "Sheraden                                                               1   \n",
       "South Oakland                                                          1   \n",
       "South Shore                                                            1   \n",
       "South Side Flats                                                       1   \n",
       "South Side Slopes                                                      1   \n",
       "Spring Garden                                                          1   \n",
       "Spring Hill-City View                                                  1   \n",
       "Squirrel Hill North                                                    1   \n",
       "Squirrel Hill South                                                    1   \n",
       "St. Clair                                                              1   \n",
       "Stanton Heights                                                        1   \n",
       "Strip District                                                         1   \n",
       "Summer Hill                                                            1   \n",
       "Swisshelm Park                                                         1   \n",
       "Terrace Village                                                        1   \n",
       "Troy Hill                                                              1   \n",
       "Upper Hill                                                             1   \n",
       "Upper Lawrenceville                                                    1   \n",
       "West End                                                               1   \n",
       "West Oakland                                                           1   \n",
       "Westwood                                                               1   \n",
       "Windgap                                                                1   \n",
       "\n",
       "                           Margin of Error; Total: - With wage or salary income  \\\n",
       "Neighborhood                                                                      \n",
       "Allegheny Center                                                           1      \n",
       "Allegheny West                                                             1      \n",
       "Allentown                                                                  1      \n",
       "Arlington                                                                  1      \n",
       "Arlington Heights                                                          1      \n",
       "Banksville                                                                 1      \n",
       "Bedford Dwellings                                                          1      \n",
       "Beechview                                                                  1      \n",
       "Beltzhoover                                                                1      \n",
       "Bloomfield                                                                 1      \n",
       "Bluff                                                                      1      \n",
       "Bon Air                                                                    1      \n",
       "Brighton Heights                                                           1      \n",
       "Brookline                                                                  1      \n",
       "California-Kirkbride                                                       1      \n",
       "Carrick                                                                    1      \n",
       "Central Business District                                                  1      \n",
       "Central Lawrenceville                                                      1      \n",
       "Central Northside                                                          1      \n",
       "Central Oakland                                                            1      \n",
       "Chartiers City                                                             1      \n",
       "Chateau                                                                    1      \n",
       "Crafton Heights                                                            1      \n",
       "Crawford-Roberts                                                           1      \n",
       "Duquesne Heights                                                           1      \n",
       "East Allegheny                                                             1      \n",
       "East Carnegie                                                              1      \n",
       "East Hills                                                                 1      \n",
       "East Liberty                                                               1      \n",
       "Elliott                                                                    1      \n",
       "...                                                                      ...      \n",
       "Perry North                                                                1      \n",
       "Perry South                                                                1      \n",
       "Point Breeze                                                               1      \n",
       "Point Breeze North                                                         1      \n",
       "Polish Hill                                                                1      \n",
       "Regent Square                                                              1      \n",
       "Ridgemont                                                                  1      \n",
       "Shadyside                                                                  1      \n",
       "Sheraden                                                                   1      \n",
       "South Oakland                                                              1      \n",
       "South Shore                                                                1      \n",
       "South Side Flats                                                           1      \n",
       "South Side Slopes                                                          1      \n",
       "Spring Garden                                                              1      \n",
       "Spring Hill-City View                                                      1      \n",
       "Squirrel Hill North                                                        1      \n",
       "Squirrel Hill South                                                        1      \n",
       "St. Clair                                                                  1      \n",
       "Stanton Heights                                                            1      \n",
       "Strip District                                                             1      \n",
       "Summer Hill                                                                1      \n",
       "Swisshelm Park                                                             1      \n",
       "Terrace Village                                                            1      \n",
       "Troy Hill                                                                  1      \n",
       "Upper Hill                                                                 1      \n",
       "Upper Lawrenceville                                                        1      \n",
       "West End                                                                   1      \n",
       "West Oakland                                                               1      \n",
       "Westwood                                                                   1      \n",
       "Windgap                                                                    1      \n",
       "\n",
       "                           Estimate; Total: - No wage or salary income  \\\n",
       "Neighborhood                                                             \n",
       "Allegheny Center                                                     1   \n",
       "Allegheny West                                                       1   \n",
       "Allentown                                                            1   \n",
       "Arlington                                                            1   \n",
       "Arlington Heights                                                    1   \n",
       "Banksville                                                           1   \n",
       "Bedford Dwellings                                                    1   \n",
       "Beechview                                                            1   \n",
       "Beltzhoover                                                          1   \n",
       "Bloomfield                                                           1   \n",
       "Bluff                                                                1   \n",
       "Bon Air                                                              1   \n",
       "Brighton Heights                                                     1   \n",
       "Brookline                                                            1   \n",
       "California-Kirkbride                                                 1   \n",
       "Carrick                                                              1   \n",
       "Central Business District                                            1   \n",
       "Central Lawrenceville                                                1   \n",
       "Central Northside                                                    1   \n",
       "Central Oakland                                                      1   \n",
       "Chartiers City                                                       1   \n",
       "Chateau                                                              1   \n",
       "Crafton Heights                                                      1   \n",
       "Crawford-Roberts                                                     1   \n",
       "Duquesne Heights                                                     1   \n",
       "East Allegheny                                                       1   \n",
       "East Carnegie                                                        1   \n",
       "East Hills                                                           1   \n",
       "East Liberty                                                         1   \n",
       "Elliott                                                              1   \n",
       "...                                                                ...   \n",
       "Perry North                                                          1   \n",
       "Perry South                                                          1   \n",
       "Point Breeze                                                         1   \n",
       "Point Breeze North                                                   1   \n",
       "Polish Hill                                                          1   \n",
       "Regent Square                                                        1   \n",
       "Ridgemont                                                            1   \n",
       "Shadyside                                                            1   \n",
       "Sheraden                                                             1   \n",
       "South Oakland                                                        1   \n",
       "South Shore                                                          1   \n",
       "South Side Flats                                                     1   \n",
       "South Side Slopes                                                    1   \n",
       "Spring Garden                                                        1   \n",
       "Spring Hill-City View                                                1   \n",
       "Squirrel Hill North                                                  1   \n",
       "Squirrel Hill South                                                  1   \n",
       "St. Clair                                                            1   \n",
       "Stanton Heights                                                      1   \n",
       "Strip District                                                       1   \n",
       "Summer Hill                                                          1   \n",
       "Swisshelm Park                                                       1   \n",
       "Terrace Village                                                      1   \n",
       "Troy Hill                                                            1   \n",
       "Upper Hill                                                           1   \n",
       "Upper Lawrenceville                                                  1   \n",
       "West End                                                             1   \n",
       "West Oakland                                                         1   \n",
       "Westwood                                                             1   \n",
       "Windgap                                                              1   \n",
       "\n",
       "                           Margin of Error; Total: - No wage or salary income  \n",
       "Neighborhood                                                                   \n",
       "Allegheny Center                                                           1   \n",
       "Allegheny West                                                             1   \n",
       "Allentown                                                                  1   \n",
       "Arlington                                                                  1   \n",
       "Arlington Heights                                                          1   \n",
       "Banksville                                                                 1   \n",
       "Bedford Dwellings                                                          1   \n",
       "Beechview                                                                  1   \n",
       "Beltzhoover                                                                1   \n",
       "Bloomfield                                                                 1   \n",
       "Bluff                                                                      1   \n",
       "Bon Air                                                                    1   \n",
       "Brighton Heights                                                           1   \n",
       "Brookline                                                                  1   \n",
       "California-Kirkbride                                                       1   \n",
       "Carrick                                                                    1   \n",
       "Central Business District                                                  1   \n",
       "Central Lawrenceville                                                      1   \n",
       "Central Northside                                                          1   \n",
       "Central Oakland                                                            1   \n",
       "Chartiers City                                                             1   \n",
       "Chateau                                                                    1   \n",
       "Crafton Heights                                                            1   \n",
       "Crawford-Roberts                                                           1   \n",
       "Duquesne Heights                                                           1   \n",
       "East Allegheny                                                             1   \n",
       "East Carnegie                                                              1   \n",
       "East Hills                                                                 1   \n",
       "East Liberty                                                               1   \n",
       "Elliott                                                                    1   \n",
       "...                                                                      ...   \n",
       "Perry North                                                                1   \n",
       "Perry South                                                                1   \n",
       "Point Breeze                                                               1   \n",
       "Point Breeze North                                                         1   \n",
       "Polish Hill                                                                1   \n",
       "Regent Square                                                              1   \n",
       "Ridgemont                                                                  1   \n",
       "Shadyside                                                                  1   \n",
       "Sheraden                                                                   1   \n",
       "South Oakland                                                              1   \n",
       "South Shore                                                                1   \n",
       "South Side Flats                                                           1   \n",
       "South Side Slopes                                                          1   \n",
       "Spring Garden                                                              1   \n",
       "Spring Hill-City View                                                      1   \n",
       "Squirrel Hill North                                                        1   \n",
       "Squirrel Hill South                                                        1   \n",
       "St. Clair                                                                  1   \n",
       "Stanton Heights                                                            1   \n",
       "Strip District                                                             1   \n",
       "Summer Hill                                                                1   \n",
       "Swisshelm Park                                                             1   \n",
       "Terrace Village                                                            1   \n",
       "Troy Hill                                                                  1   \n",
       "Upper Hill                                                                 1   \n",
       "Upper Lawrenceville                                                        1   \n",
       "West End                                                                   1   \n",
       "West Oakland                                                               1   \n",
       "Westwood                                                                   1   \n",
       "Windgap                                                                    1   \n",
       "\n",
       "[91 rows x 7 columns]"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "police_data.groupby('Neighborhood').count()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.7",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
